/**
 * Created by bob.dankert on 7/29/2016.
 */

/*
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 */

solutions.problem_12 = function () {
  var sum = 0;
  var max_factors = 20;

  for (var index = 1; index < 10000; index++) {
    var tri_number =  scratch.problem_12.getTriangleNumber(index);


  }
  scratch.problem_12 = {};
  return sum;
};

scratch.problem_12 = {};
scratch.problem_12.getTriangleNumber = function (index) {
  return (index * (index + 1)) / 2;
};