/**
 * Created by bob.dankert on 7/27/2016.
 */
solutions.problem_2 = function () {
  /*
   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
   */
  var sum = 2;
  var index1 = 1;
  var index2 = 2;
  var new_val;
  while ((new_val = index1 + index2) < 4000000) {
    if (new_val % 2 == 0)
      sum += new_val;
    index1 = index2;
    index2 = new_val;
  }

  return sum;
};